language: python
python:
  - 3.6
  - 3.5
env:
  - DJANGO=21
  - DJANGO=20
  - DJANGO=111

matrix:
  fast_finish: true
  include:
    - python: 3.4
      env: DJANGO=111
    - python: 3.4
      env: DJANGO=18

    - python: 2.7
      env: DJANGO=111
    - python: 2.7
      env: DJANGO=18

sudo: true
install:
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - pip install tox

script: tox -e py$(python -c 'import sys;print("".join(map(str, sys.version_info[:2])))')-dj${DJANGO}
